image: "rust:alpine"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/

stages:
  - build

linux-musl:
  stage: build
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/swaystatus
  only:
    - tags
