image: "rust:alpine"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - target/

stages:
  - lint
  - build

lint-linux-musl:
  stage: lint
  before_script:
    - rustup component add clippy
  script:
    # fail when encountering warnings from the clippy::all category
    - cargo clippy -- -D clippy::all

build-linux-musl:
  stage: build
  script:
    - cargo build --release --target x86_64-unknown-linux-musl
  artifacts:
    paths:
      - target/x86_64-unknown-linux-musl/release/swaystatus
  only:
    - tags
